package com.training.core.constant;

public class CoreConstant {
 public static final String RESERVE_WORDS_FOR_DATA_TYPE="RESERVE_WORDS_FOR_DATA_TYPE";
 public static final String RESERVE_WORDS_FOR_CLASS="RESERVE_WORDS_FOR_CLASS";
 public static final String RESERVE_WORDS_FOR_OBJECT="RESERVE_WORDS_FOR_OBJECT";
 public static final String RESERVE_WORDS_FOR_MODIFIERS="RESERVE_WORDS_FOR_MODIFIERS";
 public static final String RESERVE_WORDS_FOR_LITERALS="RESERVE_WORDS_FOR_LITERALS";
 public static final String RESERVE_WORDS_FOR_UNUSED_KEYWORDS="RESERVE_WORDS_FOR_UNUSED_KEYWORDS";
 public static final String RESERVE_WORDS_FOR_FLOW_CONTROL="RESERVE_WORDS_FOR_FLOW_CONTROL";
 public static final String RESERVE_WORDS_FOR_EXCEPTION_HANDLING="RESERVE_WORDS_FOR_EXCEPTION_HANDLING";
}
